#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

# brew cask install docker
brew install node || brew upgrade node

pushd "$DIR"
npm install
popd

# PATH="$DIR/node_modules/.bin/:$PATH" "$DIR/node_modules/.bin/elm" make "$DIR/src/Main.elm"
